//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by 3DPMax.rc
//
#define IDD_ABOUTBOX                    100
#define IDB_SPLASH1                     102
#define IDR_MAINFRAME                   128
#define IDR_MY3DPMTYPE                  129
#define IDD_3DPSTA                      131
#define IDD_MODAL_PROPERTY              132
#define IDD_SLICE                       133
#define IDD_COMMUNICATION               134
#define IDD_DIALOG_CHECK                135
#define IDD_DIALOG_STL                  136
#define IDD_PRIMOD                      137
#define IDD_CHKPLA                      139
#define IDB_SPLASH                      141
#define IDD_DIALOG_MODBUSRTU            144
#define IDD_DIALOG_MODBUS_TCP           146
#define IDC_EDIT1                       1000
#define IDC_EDIT2                       1001
#define IDC_EDIT3                       1002
#define IDC_RADIO1                      1002
#define IDC_RADIO_01                    1002
#define IDC_EDIT4                       1003
#define IDC_NUMBER                      1003
#define IDC_COMBO1                      1004
#define IDC_RADIO3                      1004
#define IDC_EDIT5                       1004
#define IDC_RADIO_02                    1004
#define IDC_COMBO_CommSelect            1004
#define IDC_COMBO_CommSelect_RTU        1004
#define IDC_COMBO2                      1005
#define IDC_RADIO4                      1005
#define IDC_EDIT6                       1005
#define IDC_SLIDER_CENG                 1005
#define IDC_RADIO_03                    1005
#define IDC_COMBO_BaudRate_Select       1005
#define IDC_COMBO_BaudRate_Select_RTU   1005
#define IDC_COMBO3                      1006
#define IDC_RADIO5                      1006
#define IDC_EDIT7                       1006
#define IDC_BUT_GET_FILE                1006
#define IDC_RADIO_04                    1006
#define IDC_COMBO_Date_Select           1006
#define IDC_COMBO_Date_Select_RTU       1006
#define IDC_COMBO_Data_Select_RTU       1006
#define IDC_COMBO4                      1007
#define IDC_RADIO6                      1007
#define IDC_EDIT8                       1007
#define IDC_BUT_CLEAR                   1007
#define IDC_RADIO_05                    1007
#define IDC_COMBO_StopBit               1007
#define IDC_COMBO_StopBit_RTU           1007
#define IDC_COMBO5                      1008
#define IDC_RADIO7                      1008
#define IDC_EDIT9                       1008
#define IDC_BUT_CANCEL                  1008
#define IDC_RADIO_06                    1008
#define IDC_COMBO_ParityCheck           1008
#define IDC_COMBO_ParityCheck_RTU       1008
#define IDC_LIST1                       1009
#define IDC_RADIO8                      1009
#define IDC_RADIO_07                    1009
#define IDC_EDIT11                      1009
#define IDC_RADIO9                      1010
#define IDC_RADIO_08                    1010
#define IDC_EDIT12                      1010
#define IDC_PROGRESS1                   1011
#define IDC_EDIT13                      1011
#define IDC_EDIT14                      1012
#define IDC_EDIT15                      1013
#define IDC_EDIT16                      1014
#define IDC_EDIT17                      1015
#define IDC_BUTTON4                     1016
#define IDC_BUT_CHECKPLA                1016
#define IDC_B_CLOSE                     1016
#define IDC_BUTTON_WRITE                1016
#define IDC_BUTTON5                     1017
#define IDC_HEIGHT                      1017
#define IDC_BUT_CANCELPLA               1017
#define IDC_BUTTON_READ                 1017
#define IDC_BUTTON6                     1018
#define IDC_EDIT_HEIGHT                 1018
#define IDC_DataCancel                  1018
#define IDC_EDIT18                      1018
#define IDC_EDIT_NUMBER                 1019
#define IDC_OK                          1020
#define IDC_CANCEL                      1021
#define IDC_CHVIEW                      1022
#define IDC_EDIT_CENG                   1023
#define IDC_BUTCENGCHECK                1024
#define IDC_BUTCENGSCAN                 1025
#define IDC_MODLENG                     1026
#define IDC_MODWID                      1027
#define IDC_MODHIGH                     1028
#define IDC_MODTRIA                     1029
#define IDC_DataOk                      1030
#define IDC_DataWrt                     1031
#define IDScomOn                        1032
#define IDScomOff                       1033
#define IDC_EDIT10                      1034
#define IDC_MSCOMM                      1036
#define IDC_BUTCANCEL                   1039
#define IDC_CENG_NUM                    1040
#define IDC_PRINT_NUM                   1041
#define IDC_BUT_OPENRTU                 1042
#define IDC_BUT_CLOSERTU                1043
#define IDC_B_READ                      1044
#define IDC_B_WRITE                     1045
#define IDC_E_RTU                       1047
#define IDC_E_REGADD                    1048
#define IDC_E_REGCOUNT                  1049
#define IDC_E_VALUE                     1050
#define IDC_R_TEXT                      1051
#define IDC_EDIT_CENGNUM                1052
#define IDC_BUT_OPEN_MSCOM              1053
#define IDC_BUT_CLOSE_MSCOM             1054
#define IDC_BUT_CLEAR_RICHEDIT          1055
#define IDC_BUTTON_CREAT_LINK           1057
#define IDC_BUTTON_START_DOWNLOAD       1058
#define IDC_BUTTON_BREAK_LINK           1059
#define IDC_BUTTON_STOP_DOWNLOAD        1060
#define IDC_RICHEDIT_R                  1061
#define IDC_EDIT_SERVER_ADDR            1062
#define IDC_EDIT_PORT                   1063
#define IDC_EDIT_DATA_ADDR              1064
#define IDC_EDIT_DATA_FLOAT             1065
#define IDC_EDIT_DATA_WRITE             1066
#define IDC_EDIT_CENG_NUM               1067
#define IDC_EDIT_PRIT_PERCENT           1068
#define IDC_BUTTON_CLEAN_TEXT           1069
#define IDC_BUTTON_WRITE_FLOAT          1070
#define ID_MENUOUTLINE                  32771
#define ID_VIEW_FRONT                   32772
#define ID_MENUPRINTER                  32773
#define ID_VIEW_LEFT                    32774
#define ID_VIEW_TOP                     32775
#define ID_VIEW_RIGHT                   32776
#define ID_VIEW_BEHIND                  32777
#define ID_VIEW_BOTTOM                  32778
#define ID_VIEW_NE_ISOMETRIC            32779
#define ID_BIN2ASC                      32780
#define ID_MODAL_PROPERTY               32781
#define ID_BUTTON_PROCESS               32782
#define ID_BUTTON_SLICE                 32784
#define ID_BUTTON_FILL                  32785
#define ID_STL_FILEIN                   32786
#define ID_FILE_CLEAR                   32787
#define ID_PRINTING                     32788
#define ID_BUTTON_CHKPLA                32796
#define ID_VIEW_SHADE                   32797
#define ID_BUTMODBUS                    32798
#define ID_BUTTON32800                  32800
#define ID_BUTTON_MODBUS_TCP            32801

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        147
#define _APS_NEXT_COMMAND_VALUE         32802
#define _APS_NEXT_CONTROL_VALUE         1071
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
